# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: video_processing.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'video_processing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16video_processing.proto\x12\x10video_processing\"n\n\nVideoFrame\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x0e\n\x06\x66ormat\x18\x04 \x01(\x05\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\x12\x10\n\x08\x66rame_id\x18\x06 \x01(\t\"|\n\x0b\x42oundingBox\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\r\n\x05width\x18\x03 \x01(\x02\x12\x0e\n\x06height\x18\x04 \x01(\x02\x12\x12\n\nclass_name\x18\x05 \x01(\t\x12\x12\n\nconfidence\x18\x06 \x01(\x02\x12\x10\n\x08\x63lass_id\x18\x07 \x01(\x05\"\xf4\x01\n\x0f\x44\x65tectionResult\x12\x10\n\x08\x66rame_id\x18\x01 \x01(\t\x12,\n\x05\x62oxes\x18\x02 \x03(\x0b\x32\x1d.video_processing.BoundingBox\x12\x1a\n\x12processing_time_ms\x18\x03 \x01(\x03\x12\x11\n\talgorithm\x18\x04 \x01(\t\x12\x41\n\x08metadata\x18\x05 \x03(\x0b\x32/.video_processing.DetectionResult.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"k\n\x0eProcessedFrame\x12\x10\n\x08\x66rame_id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0e\n\x06height\x18\x04 \x01(\x05\x12\x1a\n\x12processing_time_ms\x18\x05 \x01(\x03\"\x90\x01\n\rStreamControl\x12\x36\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32&.video_processing.StreamControl.Action\x12\x11\n\tstream_id\x18\x02 \x01(\t\"4\n\x06\x41\x63tion\x12\t\n\x05START\x10\x00\x12\x08\n\x04STOP\x10\x01\x12\t\n\x05PAUSE\x10\x02\x12\n\n\x06RESUME\x10\x03\x32\x9c\x02\n\x16VideoProcessingService\x12T\n\rDetectObjects\x12\x1c.video_processing.VideoFrame\x1a!.video_processing.DetectionResult(\x01\x30\x01\x12[\n\x15ProcessAndReturnVideo\x12\x1c.video_processing.VideoFrame\x1a .video_processing.ProcessedFrame(\x01\x30\x01\x12O\n\x0bHealthCheck\x12\x1f.video_processing.StreamControl\x1a\x1f.video_processing.StreamControlb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_processing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DETECTIONRESULT_METADATAENTRY']._loaded_options = None
  _globals['_DETECTIONRESULT_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_VIDEOFRAME']._serialized_start=44
  _globals['_VIDEOFRAME']._serialized_end=154
  _globals['_BOUNDINGBOX']._serialized_start=156
  _globals['_BOUNDINGBOX']._serialized_end=280
  _globals['_DETECTIONRESULT']._serialized_start=283
  _globals['_DETECTIONRESULT']._serialized_end=527
  _globals['_DETECTIONRESULT_METADATAENTRY']._serialized_start=480
  _globals['_DETECTIONRESULT_METADATAENTRY']._serialized_end=527
  _globals['_PROCESSEDFRAME']._serialized_start=529
  _globals['_PROCESSEDFRAME']._serialized_end=636
  _globals['_STREAMCONTROL']._serialized_start=639
  _globals['_STREAMCONTROL']._serialized_end=783
  _globals['_STREAMCONTROL_ACTION']._serialized_start=731
  _globals['_STREAMCONTROL_ACTION']._serialized_end=783
  _globals['_VIDEOPROCESSINGSERVICE']._serialized_start=786
  _globals['_VIDEOPROCESSINGSERVICE']._serialized_end=1070
# @@protoc_insertion_point(module_scope)
