# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import video_processing_pb2 as video__processing__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in video_processing_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VideoProcessingServiceStub(object):
    """双向流式视频处理服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectObjects = channel.stream_stream(
                '/video_processing.VideoProcessingService/DetectObjects',
                request_serializer=video__processing__pb2.VideoFrame.SerializeToString,
                response_deserializer=video__processing__pb2.DetectionResult.FromString,
                _registered_method=True)
        self.ProcessAndReturnVideo = channel.stream_stream(
                '/video_processing.VideoProcessingService/ProcessAndReturnVideo',
                request_serializer=video__processing__pb2.VideoFrame.SerializeToString,
                response_deserializer=video__processing__pb2.ProcessedFrame.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/video_processing.VideoProcessingService/HealthCheck',
                request_serializer=video__processing__pb2.StreamControl.SerializeToString,
                response_deserializer=video__processing__pb2.StreamControl.FromString,
                _registered_method=True)


class VideoProcessingServiceServicer(object):
    """双向流式视频处理服务
    """

    def DetectObjects(self, request_iterator, context):
        """场景 1: 接收视频帧，返回检测结果（元数据）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessAndReturnVideo(self, request_iterator, context):
        """场景 2: 接收视频帧，返回处理后的视频（带标注）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """健康检查
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VideoProcessingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectObjects': grpc.stream_stream_rpc_method_handler(
                    servicer.DetectObjects,
                    request_deserializer=video__processing__pb2.VideoFrame.FromString,
                    response_serializer=video__processing__pb2.DetectionResult.SerializeToString,
            ),
            'ProcessAndReturnVideo': grpc.stream_stream_rpc_method_handler(
                    servicer.ProcessAndReturnVideo,
                    request_deserializer=video__processing__pb2.VideoFrame.FromString,
                    response_serializer=video__processing__pb2.ProcessedFrame.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=video__processing__pb2.StreamControl.FromString,
                    response_serializer=video__processing__pb2.StreamControl.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'video_processing.VideoProcessingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('video_processing.VideoProcessingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VideoProcessingService(object):
    """双向流式视频处理服务
    """

    @staticmethod
    def DetectObjects(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/video_processing.VideoProcessingService/DetectObjects',
            video__processing__pb2.VideoFrame.SerializeToString,
            video__processing__pb2.DetectionResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessAndReturnVideo(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/video_processing.VideoProcessingService/ProcessAndReturnVideo',
            video__processing__pb2.VideoFrame.SerializeToString,
            video__processing__pb2.ProcessedFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/video_processing.VideoProcessingService/HealthCheck',
            video__processing__pb2.StreamControl.SerializeToString,
            video__processing__pb2.StreamControl.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
