servers:
  http_server:
    host: 127.0.0.1
    port: 8080    

clients:
  zlm:
    host: 127.0.0.1
    port: 8888
    init_size: 5
    max_size: 20
    connect_timeout_ms: 30000
    idle_timeout_sec: 300
    max_requests_per_client: 100

logs:
  mainlog:
    level: debug
    dir: ./logs
    rotation: daily
    max_file_size_mb: 100
    max_files: 5
    console: true
    json_format: false
  errorlog:
    level: error
    dir: ./logs
    max_file_size_mb: 100
    max_files: 5
    rotation: daily
    console: true
    json_format: false

zlm:
  zlm_host: 127.0.0.1
  zlm_port: 8888
  secret: sphrh7r2VafHUILiTVyK3rm1C6hnUYpZ  

websocket:
  host: 127.0.0.1
  port: 8090
  heartbeat_interval: 10
  timeout: 30

camera_db:
  db_path: ./data/camera.db
  # 使用 SQLite3 直接 1 个连接即可
  pool_size: 1
  # host: localhost
  # port: 3306
  # name: cameras
  # user: root
  # password: ""  

user_db:
  db_path: ./data/user.db
  # 使用 SQLite3 直接 1 个连接即可
  pool_size: 1
  # host: localhost
  # port: 3306
  # name: users
  # user: root
  # password: ""
  